Feature/horarios de hoje: RSpec e Implementação
SergioAlonsoJr/Reserva-de-Salas pull request #4
Opened 2021-10-21 16:38 UTC by SergioAlonsoJr

Fiz o Cucumber, testei o cucumber, fiz o RSpec, testei o rspec, implementei a feature, passei no teste do rspec, passei no teste do cucumber.

2021-10-21 17:07 UTC, yangalli requested changes

2021-10-21 17:07 UTC, yangalli commented on app/models/appointment.rb
> +    appointment_date = Time.new(Date.today.year, Date.today.month, Date.today.day, 0, 0, 0, "UTC")
Maybe you could just put Time.zone.now here

2021-10-21 17:07 UTC, yangalli commented on app/models/appointment.rb
> +    logger.debug appointments_for_today
I don't think it's a good practice to keep this debugger. Also, you can use byebug to debug stuff

2021-10-21 17:07 UTC, yangalli commented on app/views/backoffice/dashboard/index.html.erb
> +				<% if @todays_appointments.length > 0 %>
Maybe just put: @todays_appointments, or use a guard clause in here.

2021-10-21 17:07 UTC, yangalli commented on features/dashboard_admin/horarios_de_hoje.feature
> +@wip
I think you should remove the wip before merging

2021-10-21 17:36 UTC, SergioAlonsoJr commented on app/models/appointment.rb
> +    appointment_date = Time.new(Date.today.year, Date.today.month, Date.today.day, 0, 0, 0, "UTC")
Tenho medo de mudar pra Time.zone.now  e o código parar de funcionar. Antes de colocar UTC, ele tava gerando uma divergencia de 3 horas por causa do nosso fuso horário e isso tava zoando os teste. Também notei que por padrão é usado UTC no formulário de criar os appointments (feito por alunos dos semestres passados).

 Na Sprint 3 posso ver se tem como reescrever de forma mais elegante.

2021-10-21 17:39 UTC, SergioAlonsoJr commented on app/views/backoffice/dashboard/index.html.erb
> +				<% if @todays_appointments.length > 0 %>
É possível que seja retornado um @todays_appointments de length 0, ou seja, um array vazio, e aí o if não vai funcionar como deveria.
Eu não sei como seria uma guard clause dentro da view.

2021-10-21 17:42 UTC, SergioAlonsoJr commented on features/dashboard_admin/horarios_de_hoje.feature
> +@wip
Eu acho que fiz uma confusão sobre o que a tag wip deveria fazer. Afinal, é pro cucumber executar todos os testes que NÃO tenham o @wip, ou é para executar somente os que tem @wip?

Esse teste vai ter que ser executado de novo depois que fizermos os merges das 5 features da dashboard do admin, pois todas elas convivem na mesma view e controller.

2021-10-21 17:43 UTC, SergioAlonsoJr commented on app/models/appointment.rb
> +    logger.debug appointments_for_today
Vou remover.

2021-10-22 12:00 UTC, yangalli commented on app/models/appointment.rb
> +    appointment_date = Time.new(Date.today.year, Date.today.month, Date.today.day, 0, 0, 0, "UTC")
Massa! Depois de mostro como arrumar esse ponto do timezone

2021-10-22 12:02 UTC, yangalli commented on app/views/backoffice/dashboard/index.html.erb
> +				<% if @todays_appointments.length > 0 %>
Seria tipo assim: https://campuscode.com.br/conteudos/guard-clause-em-ruby

Mas essa solução está massa. Podemos pegar para refatorar na próxima sprint :)

2021-10-22 12:02 UTC, yangalli commented on features/dashboard_admin/horarios_de_hoje.feature
> +@wip
Acho que do jeito que tá hoje vai ser necessário mesmo, erro meu!

2021-10-22 12:03 UTC, yangalli approved these changes

2021-10-22 12:03 UTC, yangalli commented
Aprovado 🚀

2021-10-22 12:08 UTC, yangalli commented on app/views/backoffice/dashboard/index.html.erb
> +				<% if @todays_appointments.length > 0 %>
Uma forma melhor, na verdade, seria criar um scope na model que encapsula esse length > 0, pra que possamos usá-la no controller. Posso te mostrar melhor essa solução depois

2021-10-22 16:52 UTC, merged